
import com.fazecast.jSerialComm.SerialPort;

import java.awt.*;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.json.*;






/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author miguel
 */




public class aq_dados_gui extends javax.swing.JFrame{
    
    static SerialPort port;
    
    static XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer( );
    
    static XYSeries series15 = new XYSeries("Sensor 15cm");
    static XYSeries series25 = new XYSeries("Sensor 25cm");
    static XYSeries series35 = new XYSeries("Sensor 35cm");
    static XYSeriesCollection dataset = new XYSeriesCollection();
    
    static int x = 0;
    
    int number=0;

    /**
     * Creates new form aq
     */
    public aq_dados_gui() {
        initComponents();
        dataset.addSeries(series15);
        dataset.addSeries(series25);
        dataset.addSeries(series35);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbbox_ports = new javax.swing.JComboBox();
        frequency_text = new javax.swing.JComboBox();
        btn_conectar = new javax.swing.JButton();
        cmbbox_baudrate = new javax.swing.JComboBox();
        jPanel_chart = new javax.swing.JPanel();
        chkbox_sensor15 = new javax.swing.JCheckBox();
        chkbox_sensor25 = new javax.swing.JCheckBox();
        chkbox_sensor35 = new javax.swing.JCheckBox();
        txtField_beta_sensor15 = new javax.swing.JTextField();
        jLabel_beta_sensor15 = new javax.swing.JLabel();
        txtField_beta_sensor25 = new javax.swing.JTextField();
        jLabel_beta_sensor25 = new javax.swing.JLabel();
        txtField_beta_sensor35 = new javax.swing.JTextField();
        jLabel_beta_sensor35 = new javax.swing.JLabel();
        jLabel_initial_voltage = new javax.swing.JLabel();
        txtField_initial_voltage = new javax.swing.JTextField();
        txtField_initialResistence_sensor15 = new javax.swing.JTextField();
        jLabel_initialResistence_sensor15 = new javax.swing.JLabel();
        txtField_initialResistence_sensor25 = new javax.swing.JTextField();
        jLabel_initialResistence_sensor25 = new javax.swing.JLabel();
        txtField_initialResistence_sensor35 = new javax.swing.JTextField();
        jLabel_initialResistence_sensor35 = new javax.swing.JLabel();
        txtField_initialTemperature_sensor = new javax.swing.JTextField();
        jLabel_initialTemperature_sensor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bancada para Controle de Fluxo de Calor");

        cmbbox_ports.setModel(new javax.swing.DefaultComboBoxModel());
        cmbbox_ports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbox_portsActionPerformed(evt);
            }
        });

        frequency_text.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"0.5", "1", "2", "5", "10"}));
        frequency_text.setSelectedItem("10");
        frequency_text.setEnabled(false);
        frequency_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyActionPerformed(evt);
            }
        });

        btn_conectar.setText("Conectar");
        btn_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectarActionPerformed(evt);
            }
        });

        txtField_initialTemperature_sensor.setText("29");
        txtField_beta_sensor15.setText("4607.3");
        txtField_beta_sensor25.setText("5181.4");
        txtField_beta_sensor35.setText("4976.9");
        txtField_initialResistence_sensor15.setText("6440");
        txtField_initialResistence_sensor25.setText("5920");
        txtField_initialResistence_sensor35.setText("6990");
        txtField_initial_voltage.setText("5.11");

        cmbbox_baudrate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9600", "14400", "19200", "28800", "38400", "57600", "115200" }));

        jPanel_chart.setBackground(new java.awt.Color(254, 254, 254));
        jPanel_chart.setLayout(new javax.swing.BoxLayout(jPanel_chart, javax.swing.BoxLayout.LINE_AXIS));

        chkbox_sensor15.setSelected(true);
        chkbox_sensor15.setText("Sensor 15cm");
        chkbox_sensor15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbox_sensor15ActionPerformed(evt);
            }
        });

        chkbox_sensor25.setText("Sensor 25cm");

        chkbox_sensor35.setText("Sensor 35cm");

        jLabel1.setText("Selecionar Porta Serial");

        jLabel2.setText("Selecionar Baudrate");

        jLabel3.setText("Exibir no Gráfico:");

        jLabel4.setText("Frequência (Hz):");
        jLabel_beta_sensor15.setText("Beta");
        jLabel_beta_sensor25.setText("Beta");
        jLabel_beta_sensor35.setText("Beta");
        jLabel_initialResistence_sensor15.setText("Resistência inicial");
        jLabel_initialResistence_sensor25.setText("Resistência inicial");
        jLabel_initialResistence_sensor35.setText("Resistência inicial");
        jLabel_initialTemperature_sensor.setText("Temperatura inicial");
        jLabel_initial_voltage.setText("Tensão de entrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(1023, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_conectar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(cmbbox_baudrate, 0, 181, Short.MAX_VALUE)
                            .addComponent(cmbbox_ports, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(frequency_text, 181, 181, 181)
                            .addComponent(chkbox_sensor15)
                            .addComponent(chkbox_sensor25)
                            .addComponent(chkbox_sensor35)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtField_initialTemperature_sensor, 181, 181, 181)
                            .addComponent(jLabel_initialTemperature_sensor)
                            .addComponent(txtField_initial_voltage, 181, 181, 181)
                            .addComponent(jLabel_initial_voltage)
                            .addComponent(txtField_beta_sensor15, 181, 181, 181)
                            .addComponent(jLabel_beta_sensor15)
                            .addComponent(txtField_beta_sensor25, 181, 181, 181)
                            .addComponent(jLabel_beta_sensor25)
                            .addComponent(txtField_beta_sensor35, 181, 181, 181)
                            .addComponent(jLabel_beta_sensor35)
                            .addComponent(txtField_initialResistence_sensor15, 181, 181, 181)
                            .addComponent(jLabel_initialResistence_sensor15)
                            .addComponent(txtField_initialResistence_sensor25, 181, 181, 181)
                            .addComponent(jLabel_initialResistence_sensor25)
                            .addComponent(txtField_initialResistence_sensor35, 181, 181, 181)
                            .addComponent(jLabel_initialResistence_sensor35)
                        )
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_conectar, cmbbox_baudrate, cmbbox_ports});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_chart, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbbox_ports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbbox_baudrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_conectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel_initialTemperature_sensor)
                            .addComponent(txtField_initialTemperature_sensor)
                            .addComponent(jLabel_initial_voltage)
                            .addComponent(txtField_initial_voltage)
                            .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkbox_sensor15)
                        .addComponent(jLabel_beta_sensor15)
                        .addComponent(txtField_beta_sensor15)
                            .addComponent(jLabel_initialResistence_sensor15)
                            .addComponent(txtField_initialResistence_sensor15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkbox_sensor25)
                        .addComponent(jLabel_beta_sensor25)
                        .addComponent(txtField_beta_sensor25)
                        .addComponent(jLabel_initialResistence_sensor25)
                        .addComponent(txtField_initialResistence_sensor25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkbox_sensor35)
                        .addComponent(jLabel_beta_sensor35)
                        .addComponent(txtField_beta_sensor35)
                        .addComponent(jLabel_initialResistence_sensor35)
                        .addComponent(txtField_initialResistence_sensor35)
                        .addComponent(jLabel4)
                        .addComponent(frequency_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbbox_portsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbox_portsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbox_portsActionPerformed

    private void frequencyActionPerformed(java.awt.event.ActionEvent evt)
    {
        Float frequency = Float.parseFloat(frequency_text.getSelectedItem().toString());
        Float millisecond = 1000 / frequency;
        String buffer = "@" + millisecond.intValue() + ";OK";
        if (port != null && port.isOpen()) {
            port.writeBytes(buffer.getBytes(), buffer.getBytes().length);
            new Thread(() -> {
                try {
                    Thread.sleep(1000);
                    clearChart();
                }
                catch (Exception e){
                    clearChart();
                    System.err.println(e);
                }
            }).start();
        }
    }

    private void btn_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectarActionPerformed
        // TODO add your handling code here:
        
        if(btn_conectar.getText().equals("Conectar")){
            //DEBUG
            System.out.println("Botão Ok");
            //DEBUG
            port = SerialPort.getCommPort(cmbbox_ports.getSelectedItem().toString());
            port.setComPortTimeouts(SerialPort.TIMEOUT_SCANNER, 0, 0);
            port.setBaudRate(Integer.parseInt(cmbbox_baudrate.getSelectedItem().toString()));

            try {
                beta15 = getFieldValue(txtField_beta_sensor15, "Beta do sensor 15", Double.MIN_VALUE, Double.MAX_VALUE);
                initialRes15 = getFieldValue(txtField_initialResistence_sensor15, "Resistência inicial do sensor 15", Double.MIN_VALUE, Double.MAX_VALUE);
                initialTemp = getFieldValue(txtField_initialTemperature_sensor, "Temperatura inicial", Double.MIN_VALUE, Double.MAX_VALUE);
                beta25 = getFieldValue(txtField_beta_sensor25, "Beta do sensor 25", Double.MIN_VALUE, Double.MAX_VALUE);
                initialRes25 = getFieldValue(txtField_initialResistence_sensor25, "Resistência inicial do sensor 25", Double.MIN_VALUE, Double.MAX_VALUE);
                beta35 = getFieldValue(txtField_beta_sensor35, "Beta do sensor 35", Double.MIN_VALUE, Double.MAX_VALUE);
                initialRes35 = getFieldValue(txtField_initialResistence_sensor35, "Resistência inicial do sensor 35", Double.MIN_VALUE, Double.MAX_VALUE);
                inputVoltage = getFieldValue(txtField_initial_voltage, "Tensão de entrada", Double.MIN_VALUE, Double.MAX_VALUE);
            } catch (Exception e) {
                return;
            }

            if(port.openPort()){
                btn_conectar.setText("Desconectar");
                cmbbox_ports.setEnabled(false);
                cmbbox_baudrate.setEnabled(false);
                txtField_initialTemperature_sensor.setEnabled(false);
                txtField_initial_voltage.setEnabled(false);
                txtField_initialResistence_sensor15.setEnabled(false);
                txtField_initialResistence_sensor25.setEnabled(false);
                txtField_initialResistence_sensor35.setEnabled(false);
                txtField_beta_sensor15.setEnabled(false);
                txtField_beta_sensor25.setEnabled(false);
                txtField_beta_sensor35.setEnabled(false);
                frequency_text.setEnabled(true);
            }
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(aq_dados_gui.class.getName()).log(Level.SEVERE, null, ex);
            }
            Thread thread =new Thread(){
            @Override
            
            public void run(){
                
                Scanner scanner = new Scanner(port.getInputStream());
				while(scanner.hasNext()) {
					try {
						 String line = scanner.nextLine();
                                                //int number = Integer.parseInt(line);
						//series.add(x++,number);
                                                //System.out.println(number);
                                                try{
                                                    JSONArray jsonArray = new JSONArray(line);
                                                    JSONObject jsonSensor15 = jsonArray.getJSONObject(0);
                                                    JSONObject jsonSensor25 = jsonArray.getJSONObject(1);
                                                    JSONObject jsonSensor35 = jsonArray.getJSONObject(2);
                                                    /*
                                                    series15.add(jsonSensor15.getBigInteger("time"), jsonSensor15.getInt("value"));
                                                    series25.add(jsonSensor25.getBigInteger("time"), jsonSensor25.getInt("value"));
                                                    series35.add(jsonSensor35.getBigInteger("time"), jsonSensor35.getInt("value"));
                                                    */
                                                    Double value15 = convertKelvinToCelsius(getTemperature(getResistance(inputVoltage*1000.0, jsonSensor15.getDouble("value"), 20000.0), beta15, initialRes15, convertCelsiusToKelvin(initialTemp)));
                                                    Double value25 = convertKelvinToCelsius(getTemperature(getResistance(inputVoltage*1000.0, jsonSensor25.getDouble("value"), 20000.0), beta25, initialRes25, convertCelsiusToKelvin(initialTemp)));
                                                    Double value35 = convertKelvinToCelsius(getTemperature(getResistance(inputVoltage*1000.0, jsonSensor35.getDouble("value"), 20000.0), beta35, initialRes35, convertCelsiusToKelvin(initialTemp)));
                                                    series15.add(x, value15);
                                                    series25.add(x, value25);
                                                    series35.add(x++, value35);

                                                    renderer.setSeriesVisible(0, chkbox_sensor15.isSelected());
                                                    renderer.setSeriesVisible(1, chkbox_sensor25.isSelected());
                                                    renderer.setSeriesVisible(2, chkbox_sensor35.isSelected());
                                                                                                                                                                
                                                    }catch(JSONException e){
                                                        System.out.println("Read from serial: " + line);
                                                        e.printStackTrace();
                                                     }
                                                
                                             } catch(Exception e) {}
				}
                                scanner.close();
                                
                        }
           
            };
            thread.start();
            }else{
            port.closePort();
            cmbbox_ports.setEnabled(true);
            cmbbox_baudrate.setEnabled(true);
            frequency_text.setEnabled(false);
            txtField_initialTemperature_sensor.setEnabled(true);
            txtField_initial_voltage.setEnabled(true);
            txtField_initialResistence_sensor15.setEnabled(true);
            txtField_initialResistence_sensor25.setEnabled(true);
            txtField_initialResistence_sensor35.setEnabled(true);
            txtField_beta_sensor15.setEnabled(true);
            txtField_beta_sensor25.setEnabled(true);
            txtField_beta_sensor35.setEnabled(true);
            btn_conectar.setText("Conectar");
            /*APAGA O GRAFICO */
            clearChart();
            /*APAGA O GRAFICO */
        }
        
    }//GEN-LAST:event_btn_conectarActionPerformed

    private Double getResistance(Double inputVoltage, Double outputVoltage, Double initialResistance)
    {
        return (initialResistance * (outputVoltage/inputVoltage)) / ((-outputVoltage/inputVoltage) + 1);
    }

    private double getFieldValue(javax.swing.JTextField field, String description, Double minValue, Double maxValue) throws Exception {
        try {
            Double value = Double.parseDouble(field.getText());
            if (value < minValue) {
                JOptionPane.showMessageDialog(field, description + " deve ser menor que " + minValue.toString(), "Erro!", JOptionPane.WARNING_MESSAGE);
                throw new Exception();
            }
            if (value > maxValue) {
                JOptionPane.showMessageDialog(field, description + " deve ser maior que " + maxValue.toString(), "Erro!", JOptionPane.WARNING_MESSAGE);
                throw new Exception();
            }
            return value;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(field, description + " deve ser um número.", "Erro!", JOptionPane.WARNING_MESSAGE);
        }
        throw new Exception();
    }

    private double getTemperature(double resistance, double beta, double initialResistance, double initialTemperature)
    {
        return Math.pow((1/initialTemperature) + (1/beta)*(Math.log(resistance/initialResistance)), -1);
    }

    private double convertKelvinToCelsius(double kelvin)
    {
        return kelvin - 273.15F;
    }

    private double convertCelsiusToKelvin(double celsius)
    {
        return celsius + 273.15F;
    }

    private void clearChart()
    {
        series15.clear();
        series25.clear();
        series35.clear();
        x=0;
    }

    private void chkbox_sensor15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbox_sensor15ActionPerformed
        // TODO add your handling code here:
               
    }//GEN-LAST:event_chkbox_sensor15ActionPerformed
   
    /**
     * @param args the command line arguments
     */
            
    public static void main(String args[]) {
                
                new aq_dados_gui().setVisible(true);
                
                Lista_Serial lista_serial=new Lista_Serial();
                SerialPort[] ports_names=lista_serial.lista_serial();
                int ports_num=lista_serial.lista_serial().length;
                
                for(int i=0; i<ports_num;i++){
                    
                cmbbox_ports.addItem(ports_names[i].getSystemPortName());
                }
                
                JFreeChart chart = ChartFactory.createXYLineChart("Bancada Fluxo de Calor","Nº de Amostras", "Temperatura ºC", dataset, PlotOrientation.VERTICAL,true,true,false);
                
                //Gerar_Grafico grafico = new Gerar_Grafico();
                //grafico.grafico(jPanel_chart);
                
                XYPlot plot = chart.getXYPlot();

                
                renderer.setSeriesPaint( 0 , Color.RED );
                renderer.setSeriesPaint( 1 , Color.BLACK );
                renderer.setSeriesPaint( 2 , Color.blue );
                renderer.setSeriesStroke( 0 , new BasicStroke( 1.5f ) );
                renderer.setSeriesStroke( 1 , new BasicStroke( 1.5f ) );
                renderer.setSeriesStroke( 2 , new BasicStroke( 1.5f ) );
                renderer.setSeriesShapesVisible(0, false);
                renderer.setSeriesShapesVisible(1, false);
                renderer.setSeriesShapesVisible(2, false);
                plot.setDomainPannable(true);
                plot.setRangePannable(true);
                plot.setDomainCrosshairVisible(true);
                plot.setRangeCrosshairVisible(true);
                plot.setRenderer(renderer);
                ValueAxis axis = plot.getDomainAxis();
                axis.setAutoRange(true);
                axis.setFixedAutoRange(60);
                
                jPanel_chart.add(new ChartPanel(chart));
                jPanel_chart.repaint();
                jPanel_chart.setVisible(true);
                
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_conectar;
    private static javax.swing.JCheckBox chkbox_sensor15;
    private static javax.swing.JTextField txtField_beta_sensor15;
    private static javax.swing.JTextField txtField_initialResistence_sensor15;
    private static javax.swing.JTextField txtField_initialTemperature_sensor;
    private static javax.swing.JCheckBox chkbox_sensor25;
    private static javax.swing.JTextField txtField_beta_sensor25;
    private static javax.swing.JTextField txtField_initialResistence_sensor25;
    private static javax.swing.JCheckBox chkbox_sensor35;
    private static javax.swing.JTextField txtField_beta_sensor35;
    private static javax.swing.JTextField txtField_initialResistence_sensor35;
    private static javax.swing.JTextField txtField_initial_voltage;
    private javax.swing.JLabel jLabel_beta_sensor15;
    private javax.swing.JLabel jLabel_beta_sensor25;
    private javax.swing.JLabel jLabel_beta_sensor35;
    private javax.swing.JLabel jLabel_initialResistence_sensor15;
    private javax.swing.JLabel jLabel_initialResistence_sensor25;
    private javax.swing.JLabel jLabel_initialResistence_sensor35;
    private javax.swing.JLabel jLabel_initialTemperature_sensor;
    private javax.swing.JLabel jLabel_initial_voltage;
    private javax.swing.JComboBox cmbbox_baudrate;
    private static javax.swing.JComboBox cmbbox_ports;
    private static javax.swing.JComboBox frequency_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JPanel jPanel_chart;
    private Double beta15;
    private Double beta25;
    private Double beta35;
    private Double initialTemp;
    private Double initialRes15;
    private Double initialRes25;
    private Double initialRes35;
    private Double inputVoltage;
    // End of variables declaration//GEN-END:variables
}
